server:
  servlet:
    context-path: /api

ip:
  base: 119.8.43.2

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456 #  改成自己的密码
    url: jdbc:mysql://${ip.base}:3306/test?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai